spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkout?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true #jdbc:mysql://172.23.0.2:3306/checkout
    usarname: hilton
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_cretion: true